In [1]:
import numpy as np
import pandas as pd


In [8]:
#create 1 dimensional array
data1 = [6, 8, 2, 4]
arr1 = np.array(data1)
arr1


array([6, 8, 2, 4])

In [10]:
#create 2-dimensional array
data2 = [[2,3,4],[5,6,1]]
arr2 = np.array(data2)
arr2

array([[2, 3, 4],
       [5, 6, 1]])

In [14]:
#dimensions
arr2.ndim

2

In [15]:
#shape
arr2.shape

(2, 3)

In [16]:
#dtype
arr1.dtype

dtype('int32')

In [19]:
#create array of zeros (you can parse length or shape of array as argument)
arr3 = np.zeros((3, 4))
arr3

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [23]:
#fill the whole array with certain value
arr4 = np.full((2,3), 5)
arr4

array([[5, 5, 5],
       [5, 5, 5]])

In [26]:
#specify dtype
arr5 = np.array([1, 3,  4], dtype = np.float64)
arr5.dtype

dtype('float64')

In [28]:
#array indexing and slicing
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr1[4]

4

In [32]:
arr1[2:4]

array([2, 3])

In [34]:
#elements with minus sign means start counting from the last element
arr1[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [36]:
#omitted fields means start from the beginning or stop at the end of the array
arr1[4:]

array([4, 5, 6, 7, 8, 9])